Uikit multistage keyboard (Japanese, Chinese)
JetBrains/skiko pull request #516
Opened 2022-03-10 14:23 UTC by Rsedaikin

2022-03-11 09:58 UTC, olonho commented on skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoViewController.kt
>          }
Maybe null check?

2022-04-28 09:56 UTC, dima-avdeev-jb approved these changes

2022-04-28 10:01 UTC, dima-avdeev-jb approved these changes

2022-04-28 10:01 UTC, dima-avdeev-jb commented on skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoViewController.kt
>          }
add null check

2022-04-30 10:34 UTC, dima-avdeev-jb requested changes
Found bugs with last character replacement

2022-09-09 13:09 UTC, closed without merging