Make rundown rendering bandaid(or not) fix for incorrect frame scheduling
JetBrains/skiko pull request #713
Opened 2023-05-19 15:26 UTC by elijah-semyonov

The initial problem was caused by frames scheduling missing every second frame 70% of time. It was reliably reproduced by logging setPaused inside MetalRedrawer, where for each two `needRedraw` and consequent unpause, only one actual draw and consequent pause were happening, and timing between draw calls was twice the minimal refresh rate timing.

This PR fixes the problem by making CADisplayLink draw at least 3 consequent frames after last redrawCall before pausing.
While it certainly improves FPS almost twice as much for both 60hz and 120hz screens (check TextDirection example in core repo), I still have some doubts about it actually solving the true reason it happens like that. Will require further investigation.

For now enjoy _smoothness_ on all iOS targets.

2023-05-19 19:26 UTC, pjBooms requested changes

2023-05-22 07:50 UTC, elijah-semyonov commented on skiko/src/iosMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.ios.kt
> +            rundownCounter = 0
No, there is only one place that tops up the counter and unpauses CADisplayLink. Good remark.

2023-05-22 10:06 UTC, elijah-semyonov commented on skiko/src/iosMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.ios.kt
> +        rundownCounter = 3
Done

2023-05-23 10:25 UTC, elijah-semyonov commented
**TODO: investigationl** was fruitfu. We indeed have deeper underlying problem, which needs solving. Check our Slack.

2023-05-23 10:25 UTC, closed without merging